language: python
python:
  - "3.6"

#command to install dependencies
install:
  - "pip install -r requirements.txt"


# command to run tests
script:
  - nosetests --with-coverage --cover=test_user
  - coverage report



after_success:
  - coveralls
  - codeclimate-test-reporter